### ISSUE TITLE
data.csv

### ISSUE THREAD

**Issue by Imaroubat** [VrotNaoborot/WuffiTapApp#2]
"Откройте data.csv файл, в поле query вставьте свой query_id"
В репе нету, ладно создал, квери вставил. Неработает.

**Comment by VrotNaoborot** [comment]
Не заметил, когда вносил изменения - случайно удалил. Сейчас закинул

**Comment by LFQO** [comment]
Data.csv так и не появился в репозитории, добавь пожалуйста
